replicaCount: 2
image:
  repository: metabase/metabase
  tag: v0.49.6
  pullPolicy: Always
database:
  type: postgres
  clusterReleaseName: cas-metabase-db
  metabaseUserSecretName: cas-metabase-db-cas-postgres-cluster-pguser-metabase
  superuserSecretName: cas-metabase-db-cas-postgres-cluster-pguser-postgres
  dbname: metabase
resources:
  limits:
    cpu: 500m
    memory: 4Gi
  requests:
    cpu: 25m
    memory: 2Gi
podLabels:
  app.kubernetes.io/component: app

# Config Jetty web server
listen:
  host: "0.0.0.0"
  port: 3000

service:
  externalPort: 80
  internalPort: 3000

livenessProbe:
  initialDelaySeconds: 120
  timeoutSeconds: 30
  failureThreshold: 6

readinessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 3
  periodSeconds: 5

# Generate k8s NetworkPolicy objects
networkPolicies:
  enable: true

prod-test-restore:
  enable: false

metabaseHPA:
  enable: false

download-cas-metabase-dags:
  image:
    tag: 69f346b134d99e9e5e6d50e16198fd4977fc3264 # pragma: allowlist secret
  airflowEndpoint: https://cas-airflow-dev.apps.silver.devops.gov.bc.ca
  dagId: fetch_and_save_dag_from_github
  helm:
    hook: "pre-install,pre-upgrade"
<<<<<<< HEAD

patroni-migration:
  migrationJob:
    ignoreRoles:
      - metabase
      - postgres

  deployment:
    name: cas-metabase
    # for the KNP
    sourceReleaseName: cas-metabase
    targetReleaseName: cas-metabase-db

  from:
    secretName: cas-metabase-patroni
    host: ~
    passwordSecretKey: password-superuser
    port: 5432
    user: postgres
    db: metabase

  to:
    superuserSecretName: cas-metabase-db-cas-postgres-cluster-pguser-postgres
    appuserSecretName: cas-metabase-db-cas-postgres-cluster-pguser-metabase
=======
>>>>>>> c383af6 (chore: removing dependency charts and values)
