route:
  enable: true
  host: cas-metabase.nrs.gov.bc.ca

download-cas-metabase-dags:
  airflowEndpoint: https://cas-airflow-prod.apps.silver.devops.gov.bc.ca

metabaseHPA:
  enable: true
  minReplicas: 2
  maxReplicas: 5
  avgUtilization: 350
