route:
  enable: true
  host: cas-metabase-test.apps.silver.devops.gov.bc.ca

image:
  psql:
    repository: postgres
    pullPolicy: Always
    tag: "15"

download-cas-metabase-dags:
  airflowEndpoint: https://cas-airflow-test.apps.silver.devops.gov.bc.ca

metabaseHPA:
  enable: true
  minReplicas: 2
  maxReplicas: 5
  avgUtilization: 350
