apiVersion: v2
name: cas-metabase-pg-version-upgrade
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: pg-version-upgrade
    version: 0.0.2
    repository: https://bcgov.github.io/cas-postgres
