# Dev values for cas-registration.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

environment: dev

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
