replicaCount: 1
environment: ~

storageSize: 1Gi

# Needs to match the "namespace_apps" value in the terraform provisioning chart
gcsNamespace: ~

terraform-bucket-provision:
  terraform:
    namespace_apps: '["obps-backups"]'
    workspace: postgres

metabase:
  prefix: ~
  environment: ~
