{{- if .Values.metabaseHPA.enable }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "cas-metabase.fullname" . }}-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "cas-metabase.fullname" . }}
    apiVersion: apps/v1
  minReplicas: {{ .Values.metabaseHPA.minReplicas }}
  maxReplicas: {{ .Values.metabaseHPA.maxReplicas }}
  targetCPUUtilizationPercentage: 80
{{- end }}
