apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cas-metabase.fullname" . }}-create-user-db-{{ .Release.Revision }}-{{ randAlphaNum 5 | lower }}
  labels: {{ include "cas-metabase.labels" . | nindent 4 }}
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 10
  template:
    metadata:
      name: {{ template "cas-metabase.fullname" . }}-create-user-db
      labels: {{ include "cas-metabase.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ template "cas-metabase.fullname" . }}-create-user-db
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          image: {{ index .Values "cas-postgres" "patroni" "image" "repository" }}:{{ index .Values "cas-postgres" "patroni" "image" "tag" }}
          env:
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              valueFrom:
              secretKeyRef:
                name: {{ .Values.database.superUserSecretName }}
                key: user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.superUserSecretName }}
                  key: password
            - name: PGPORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.superUserSecretName }}
                  key: pgbouncer-port
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.superUserSecretName }}
                  key: pgbouncer-host
            - name: METABASE_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: {{ template "cas-metabase.fullname" . }}
            - name: METABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: {{ template "cas-metabase.fullname" . }}
            - name: METABASE_DATABASE
              value: {{ .Values.database.dbname | quote }}
          command:
                - /usr/bin/env
                - bash
                - -c
                - |
                  set -euo pipefail;
                  create-user-db -d $(METABASE_DATABASE) -u $(METABASE_USER) -p $(METABASE_PASSWORD) --owner;
      restartPolicy: Never
