{{- if .Values.route.enable }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "cas-metabase.fullname" . }}
  labels:
{{ include "cas-metabase.labels" . | indent 4 }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin

spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: metabase
{{- if .Values.metabase.nginxSidecar.sslTermination }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: passthrough
{{- end }}
  to:
    kind: Service
    name:  {{ template "cas-metabase.fullname" . }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - status: 'True'
      type: Admitted
    host: {{ .Values.route.host }}
    routerName: router
    wildcardPolicy: None
{{- end }}
