{{- if .Values.route.enable }}
{{- $route := (lookup "route.openshift.io/v1" "Route" .Release.Namespace "cas-metabase" ) }}
{{- $certificate := "" }}
{{- $key := "" }}
{{- $caCertificate := "" }}
{{- if $route }}
{{- $certificate = $route.spec.tls.certificate }}
{{- $key = $route.spec.tls.key }}
{{- $caCertificate = $route.spec.tls.caCertificate }}
{{- end -}}

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "cas-metabase.fullname" . }}
  labels:
{{ include "cas-metabase.labels" . | nindent 4 }}
    {{- if .Values.route.certbotManaged }}
    certbot-managed: {{ .Values.route.certbotManaged | quote }}
    {{- end }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin

spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: {{ template "cas-metabase.fullname" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    {{- if $certificate }}
    certificate: {{ $certificate | quote }}
    key: {{ $key | quote }}
    caCertificate: {{ $caCertificate | quote }}
    {{- end }}
  to:
    kind: Service
    name: {{ template "cas-metabase.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
