apiVersion: v1
kind: Service
metadata:
  name: {{ template "cas-metabase.fullname" . }}
  labels: {{ include "cas-metabase.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ template "cas-metabase.fullname" . }}
  selector: {{ include "cas-metabase.selectorLabels" . | nindent 4 }}
