# Values file to be passed to a deployment of https://github.com/bcgov/cas-postgres/tree/develop/helm/cas-postgres-cluster

# dev, test, prod
environment: ~

postgresCluster:
  postgres:
    replicaCount: 3
  pgbouncer:
    replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  # The "users" value(s) is passed to the crunchy postgres operator to create the database.
  # See https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/user-management
  users:
    - name: postgres
      options: "SUPERUSER"
    - name: metabase
      databases:
        - metabase

gcsBackups:
  enable: true
  # Needs to match the "namespace_apps" value in the terraform provisioning chart.
  # example syntax: bucketName
  bucketName: mb-pgo-backups

terraform-bucket-provision:
  terraform:
    # example syntax: '["bucketName"]'
    namespace_apps: '["mb-pgo-backups"]'
    # !important: unique for the deployment
    workspace: metabase-pgo

# To configure a KNP allowing external access, for metabase for example
external-access:
  enabled: false
