kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "patroni-migration.fullname" . }}-internal-by-release
  labels: {{ include "patroni-migration.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-100"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed,before-hook-creation"
spec:
  podSelector:
    matchLabels:
      release: {{ .Values.deployment.releaseName }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              release: {{ include "patroni-migration.name" . }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: {{ include "patroni-migration.name" . }}
              