# Values file to be passed to a deployment of https://github.com/bcgov/cas-postgres/tree/develop/helm/cas-postgres-cluster

# dev, test, prod
environment: ~

postgresCluster:
  postgres:
    replicaCount: 1
  pgbouncer:
    replicaCount: 1

  # The "users" value(s) is passed to the crunchy postgres operator to create the database.
  # See https://access.crunchydata.com/documentation/postgres-operator/latest/tutorials/basic-setup/user-management
  users:
    - name: postgres
      options: "SUPERUSER"

gcsBackups:
  enable: false

# To configure a KNP allowing external access, for metabase for example
external-access:
  enabled: false
