name: Lint Helm Chart

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  make-lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'
      - uses: actions/checkout@v2
      - name: Authenticate to OpenShift Linter namespace
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_LINTER_TOKEN }}
          insecure_skip_tls_verify: true
      - run: make lint_chart
